# Generated by Django 5.0.6 on 2024-05-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
