# Generated by Django 5.0.6 on 2024-05-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_schedule_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
