# Generated by Django 5.0.6 on 2024-05-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workplace_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='warranty',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
