# Generated by Django 5.0.6 on 2024-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_service_payment_alter_service_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundfeedback',
            name='answer2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
